server:
  port: 8000
  
spring:
  application:
    name: vaneu-cloud-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848    #指定Nacos服务地址
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080   #指定Sentinel DashBoard服务地址
        port: 9000                  #默认9000端口，假如被占用会自动从9000开始依次+1扫描，直至找到未被占用的端口
      
    #gateway组件相关配置
    gateway:
      discovery:
        locator:
          enabled: true #开启基于服务的注册和发现的路由转发,默认轮询模式
      routes:        - id: vaneu-cloud-service-order
          uri: lb://vaneu-cloud-service-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: vaneu-cloud-service-user
          uri: lb://vaneu-cloud-service-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
#      routes: #路由配置
#        - id: vaneu-cloud-service-user #路由名称,不配默认为UUID
#          uri: lb://vaneu-cloud-service-user #满足断言的路由到此服务
#          predicates: #为一个数组，每个规则为并且的关系
#            - Path=/api-user/** #断言表达式,如果args不写key的，会自动生成一个id，如下会生成一个xxx0的key，值为/foo/*
#          filters: #请求路由转发前执行的filter,为数组
#            - StripPrefix=1  #缩写,和name=StripPrefix,args,参数=1是一个意思,该过滤器为路由转发过滤去
            